### ISSUE TITLE
cant use interactive training

### ISSUE THREAD

**Issue by jkaczmarzynski** [openshift-evangelists/intro-katacoda#116] opened 2017-12-29 14:16 UTC
for example https://learn.openshift.com/introduction/getting-started/ i cant use this training. When i click on start buttom nothing happends. When I log in with my email and password still doesnt work.

**Comment by BenHall** [comment] 2017-12-29 19:15
Closing as duplicate of #115

**Closed by BenHall** 2017-12-29 19:15 UTC
