### ISSUE TITLE
Connecting to a Database Using Port Forwarding - missing postgresql-ephemeral template?

### ISSUE THREAD

**Issue by BenHall** [openshift-evangelists/intro-katacoda#108] opened 2017-12-20 13:25 UTC
Based on https://twitter.com/elessar_ch/status/943471919524929537

**Comment by mhausenblas** [comment] 2017-12-20 13:35
@GrahamDumpleton is this yours?

**Comment by GrahamDumpleton** [comment] 2017-12-20 20:05
It should be loaded, but I have seen this issue myself a few times in last few days when I was working in test area. The whole env-init.sh file was not being run, it would stop part way through and so wouldn't get to load all templates. Not sure what is going on, likely some timing issue. Maybe things running slow enough to startup that openshift project not created yet. We may have to come up with some additional looping check to see whether project exists before loading templates if this keeps happening.

**Comment by GrahamDumpleton** [comment] 2017-12-20 23:02
In this case it is because the ``env-init.sh`` does things in sub optimal order. This was realised after that scenario was written when working on other ones but didn't think to go back and check other scenarios.

The issue is indeed caused by OpenShift being too slow to start up, with the ``openshift`` project not being created in time before templates are loaded.

There is already one loop in the file to check for readiness with:

```
ssh root@host01 'for i in {1..200}; do oc policy add-role-to-user system:image-puller system:anonymous && break || sleep 1; done'
```

but even if templates loaded after that, is no guarantee will work. So will likely need to have a loop to check explicitly for existence of ``openshift`` project before loading templates.

A similar issue has been showing up with 3.7 GA playground where image streams are not being loaded. If the image streams are actually being loaded, which still need to verify they even are with 3.7 GA startup scripts, it too may need a looping check on whether ``openshift`` project exists before loading image streams.

**Comment by GrahamDumpleton** [comment] 2017-12-21 01:37
Example of looping construct for check if project exists.

```
ssh root@host01 "yum install -y postgresql socat"
ssh root@host01 'for i in {1..200}; do oc policy add-role-to-user system:image-puller system:anonymous && break || sleep 1; done'
ssh root@host01 "docker pull centos/postgresql-95-centos7:latest"
ssh root@host01 'for i in {1..200}; do oc get project/openshift && break || sleep 1; done'
ssh root@host01 "oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/postgresql-ephemeral-template.json -n openshift"
```

This is going to have to be done in all cases where import templates or images into the openshift project.

**Comment by GrahamDumpleton** [comment] 2017-12-24 05:54
This should be fixed now.

**Closed by GrahamDumpleton** 2017-12-24 05:54 UTC
